# -*- coding: utf-8 -*-
"""RL PBL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18J4Fa6l9O1mkeApK8SzLA56TnRUdvF-_
"""

import streamlit as st
import numpy as np
import random
import streamlit.components.v1 as components

st.title("🚦 RL-Based Traffic Control (Smooth Animation)")

# ------------------------------
# RL ENV
# ------------------------------
class TrafficEnv:
    def __init__(self):
        self.state = np.array([10,10,10,10])

    def reset(self):
        self.state = np.random.randint(0, 20, size=4)
        return tuple(self.state)

    def step(self, action):
        if action == 0:
            self.state[0] = max(0, self.state[0] - 5)
            self.state[1] = max(0, self.state[1] - 5)
        else:
            self.state[2] = max(0, self.state[2] - 5)
            self.state[3] = max(0, self.state[3] - 5)

        self.state += np.random.randint(0, 3, size=4)
        reward = -np.sum(self.state)
        return tuple(self.state), reward

def discretize(state):
    return tuple(min(19, s) for s in state)

# ------------------------------
# TRAIN BUTTON
# ------------------------------
if st.button("🚀 Train RL Agent"):
    env = TrafficEnv()
    q_table = np.zeros((20,20,20,20,2))

    alpha, gamma, epsilon = 0.1, 0.9, 1.0

    # TRAIN
    for ep in range(150):
        state = discretize(env.reset())

        for _ in range(50):
            if random.random() < epsilon:
                action = random.choice([0,1])
            else:
                action = np.argmax(q_table[state])

            next_state, reward = env.step(action)
            next_state = discretize(next_state)

            q_table[state][action] += alpha * (
                reward + gamma * np.max(q_table[next_state]) - q_table[state][action]
            )

            state = next_state

        epsilon *= 0.98

    st.success("✅ Training Done!")

    # ------------------------------
    # GENERATE ACTION SEQUENCE
    # ------------------------------
    env = TrafficEnv()
    state = discretize(env.reset())

    actions = []

    for _ in range(300):
        action = int(np.argmax(q_table[state]))
        actions.append(action)

        state, _ = env.step(action)
        state = discretize(state)

    st.session_state.actions = actions

# ------------------------------
# ANIMATION
# ------------------------------
if "actions" in st.session_state:

    actions_js = str(st.session_state.actions)

    html_code = f"""
    <canvas id="sim" width="600" height="600"></canvas>

    <script>
    const canvas = document.getElementById("sim");
    const ctx = canvas.getContext("2d");

    let actions = {actions_js};
    let step = 0;

    let carsNS = [];
    let carsEW = [];

    function spawnCars() {{
        if (Math.random() < 0.05) carsNS.push({{x:290, y:0}});
        if (Math.random() < 0.05) carsEW.push({{x:0, y:290}});
    }}

    function moveCars(signal) {{
        if (signal === 0) {{
            carsNS.forEach(c => c.y += 2);
        }} else {{
            carsEW.forEach(c => c.x += 2);
        }}

        carsNS = carsNS.filter(c => c.y < 600);
        carsEW = carsEW.filter(c => c.x < 600);
    }}

    function drawRoads() {{
        ctx.fillStyle = "#555";
        ctx.fillRect(250, 0, 100, 600);
        ctx.fillRect(0, 250, 600, 100);
    }}

    function drawCars() {{
        ctx.fillStyle = "cyan";
        carsNS.forEach(c => ctx.fillRect(c.x, c.y, 10, 20));

        ctx.fillStyle = "yellow";
        carsEW.forEach(c => ctx.fillRect(c.x, c.y, 20, 10));
    }}

    function drawSignals(signal) {{
        ctx.fillStyle = (signal === 0) ? "green" : "red";
        ctx.beginPath();
        ctx.arc(300, 200, 10, 0, Math.PI*2);
        ctx.fill();

        ctx.fillStyle = (signal === 1) ? "green" : "red";
        ctx.beginPath();
        ctx.arc(200, 300, 10, 0, Math.PI*2);
        ctx.fill();
    }}

    function loop() {{
        ctx.clearRect(0, 0, 600, 600);

        let signal = actions[step % actions.length];

        drawRoads();
        spawnCars();
        moveCars(signal);
        drawCars();
        drawSignals(signal);

        step++;

        requestAnimationFrame(loop);
    }}

    loop();
    </script>
    """

    components.html(html_code, height=620)