# -*- coding: utf-8 -*-
"""RL PBL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18J4Fa6l9O1mkeApK8SzLA56TnRUdvF-_
"""

import streamlit as st
import numpy as np
import random
import time
import matplotlib.pyplot as plt

st.set_page_config(layout="centered")
st.title("🚦 AI Smart Traffic Control System")

# ------------------------------
# ENVIRONMENT
# ------------------------------
class TrafficEnv:
    def __init__(self):
        self.state = np.array([10,10,10,10])  # N,S,E,W

    def reset(self):
        self.state = np.random.randint(0, 20, size=4)
        return tuple(self.state)

    def step(self, action):
        if action == 0:
            self.state[0] = max(0, self.state[0] - 5)
            self.state[1] = max(0, self.state[1] - 5)
        else:
            self.state[2] = max(0, self.state[2] - 5)
            self.state[3] = max(0, self.state[3] - 5)

        self.state += np.random.randint(0, 3, size=4)
        reward = -np.sum(self.state)
        return tuple(self.state), reward

def discretize(state):
    return tuple(min(19, s) for s in state)

# ------------------------------
# TRAINING
# ------------------------------
episodes = st.sidebar.slider("Episodes", 50, 300, 150)

if st.sidebar.button("🚀 Train Agent"):
    env = TrafficEnv()
    q_table = np.zeros((20,20,20,20,2))

    alpha, gamma, epsilon = 0.1, 0.9, 1.0
    rewards = []

    for ep in range(episodes):
        state = discretize(env.reset())
        total = 0

        for _ in range(50):
            if random.random() < epsilon:
                action = random.choice([0,1])
            else:
                action = np.argmax(q_table[state])

            next_state, reward = env.step(action)
            next_state = discretize(next_state)

            q_table[state][action] += alpha * (
                reward + gamma * np.max(q_table[next_state]) - q_table[state][action]
            )

            state = next_state
            total += reward

        epsilon *= 0.98
        rewards.append(total)

    st.session_state.q_table = q_table
    st.session_state.rewards = rewards
    st.success("✅ Training Completed!")

# ------------------------------
# GRAPH
# ------------------------------
if "rewards" in st.session_state:
    st.subheader("📊 Learning Curve")
    st.line_chart(st.session_state.rewards)

# ------------------------------
# SIMULATION
# ------------------------------
if "q_table" in st.session_state:
    st.subheader("🎮 Live Simulation")

    placeholder = st.empty()
    stats_box = st.empty()

    env = TrafficEnv()
    state = discretize(env.reset())

    cars_ns = []
    cars_ew = []

    passed = 0

    for step in range(80):
        action = np.argmax(st.session_state.q_table[state])
        state, _ = env.step(action)
        state = discretize(state)

        # spawn cars
        if random.random() < 0.3:
            cars_ns.append([0.48, 1.0])
        if random.random() < 0.3:
            cars_ew.append([0.0, 0.48])

        # move cars
        if action == 0:  # NS green
            for c in cars_ns:
                c[1] -= 0.05
        else:  # EW green
            for c in cars_ew:
                c[0] += 0.05

        # remove cars & count passed
        new_ns = []
        for c in cars_ns:
            if c[1] > 0:
                new_ns.append(c)
            else:
                passed += 1
        cars_ns = new_ns

        new_ew = []
        for c in cars_ew:
            if c[0] < 1:
                new_ew.append(c)
            else:
                passed += 1
        cars_ew = new_ew

        waiting = len(cars_ns) + len(cars_ew)

        # ---------------- DRAW ----------------
        fig, ax = plt.subplots()

        # roads
        ax.add_patch(plt.Rectangle((0.45,0),0.1,1))
        ax.add_patch(plt.Rectangle((0,0.45),1,0.1))

        # cars (rectangles)
        for c in cars_ns:
            ax.add_patch(plt.Rectangle((c[0],c[1]),0.02,0.04))
        for c in cars_ew:
            ax.add_patch(plt.Rectangle((c[0],c[1]),0.04,0.02))

        # signals
        if action == 0:
            ax.add_patch(plt.Circle((0.52,0.7),0.02, color='green'))
            ax.add_patch(plt.Circle((0.3,0.52),0.02, color='red'))
            signal_text = "NS GREEN"
        else:
            ax.add_patch(plt.Circle((0.52,0.7),0.02, color='red'))
            ax.add_patch(plt.Circle((0.3,0.52),0.02, color='green'))
            signal_text = "EW GREEN"

        ax.set_xlim(0,1)
        ax.set_ylim(0,1)
        ax.axis("off")

        placeholder.pyplot(fig)

        # stats display
        stats_box.markdown(f"""
        ### 📊 Live Stats
        - 🚗 Cars Passed: **{passed}**
        - ⏳ Waiting Cars: **{waiting}**
        - 🚦 Signal: **{signal_text}**
        """)

        time.sleep(0.15)

    st.success("Simulation Finished ✅")